[workspace]
resolver = "3"
members = ["crates/*", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Levi Laine shiueo.csh@gmail.com", "Feral rw70578@gmail.com"]
repository = "https://github.com/JetQLs/JetORM"
rust-version = "1.96.0"
description = ""

[workspace.lints.clippy]
too_many_arguments = "allow"
module_inception = "allow"

[workspace.dependencies]
# Internal crates

# External dependencies

