use jetorm_dialect::postgres::ddl::{render_change, render_changes};
use jetorm_entity::{ColumnType, ReferentialAction};
use jetorm_schema::{ColumnDef, ForeignKeyDef, SchemaChange, TableDef, TableName};

fn users_table() -> TableDef {
    TableDef::new(TableName::qualified("public", "users"))
        .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
        .with_column(ColumnDef::new("name", ColumnType::Text))
        .with_column(
            ColumnDef::new("email", ColumnType::Text)
                .nullable()
                .unique(),
        )
        .with_primary_key(vec!["id".to_owned()])
}

#[test]
fn create_table_renders_identity_constraints_and_key() {
    let statements =
        render_change(&SchemaChange::CreateTable(users_table())).expect("create renders");
    assert_eq!(
        statements,
        ["CREATE TABLE \"public\".\"users\" (\
             \"email\" text UNIQUE, \
             \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, \
             \"name\" text NOT NULL, \
             PRIMARY KEY (\"id\"))"]
    );
}

#[test]
fn column_changes_render_single_statements() {
    let table = TableName::qualified("public", "users");
    let cases: Vec<(SchemaChange, &str)> = vec![
        (
            SchemaChange::AddColumn {
                table: table.clone(),
                column: ColumnDef::new("bio", ColumnType::Text).nullable(),
            },
            "ALTER TABLE \"public\".\"users\" ADD COLUMN \"bio\" text",
        ),
        (
            SchemaChange::DropColumn {
                table: table.clone(),
                column: "bio".to_owned(),
            },
            "ALTER TABLE \"public\".\"users\" DROP COLUMN \"bio\"",
        ),
        (
            SchemaChange::RenameColumn {
                table: table.clone(),
                from: "name".to_owned(),
                to: "full_name".to_owned(),
            },
            "ALTER TABLE \"public\".\"users\" RENAME COLUMN \"name\" TO \"full_name\"",
        ),
        (
            SchemaChange::AlterColumnType {
                table: table.clone(),
                column: "email".to_owned(),
                from: ColumnType::Text,
                to: ColumnType::Json,
            },
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"email\" TYPE jsonb \
             USING \"email\"::jsonb",
        ),
        (
            SchemaChange::SetNullable {
                table: table.clone(),
                column: "email".to_owned(),
                nullable: false,
            },
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"email\" SET NOT NULL",
        ),
        (
            SchemaChange::SetNullable {
                table: table.clone(),
                column: "email".to_owned(),
                nullable: true,
            },
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"email\" DROP NOT NULL",
        ),
        (
            SchemaChange::SetUnique {
                table: table.clone(),
                column: "email".to_owned(),
                unique: true,
            },
            "ALTER TABLE \"public\".\"users\" ADD CONSTRAINT \"users_email_key\" \
             UNIQUE (\"email\")",
        ),
        (
            SchemaChange::SetUnique {
                table: table.clone(),
                column: "email".to_owned(),
                unique: false,
            },
            "ALTER TABLE \"public\".\"users\" DROP CONSTRAINT \"users_email_key\"",
        ),
        (
            SchemaChange::SetAutoIncrement {
                table: table.clone(),
                column: "id".to_owned(),
                auto_increment: true,
            },
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"id\" \
             ADD GENERATED BY DEFAULT AS IDENTITY",
        ),
        (
            SchemaChange::SetAutoIncrement {
                table,
                column: "id".to_owned(),
                auto_increment: false,
            },
            "ALTER TABLE \"public\".\"users\" ALTER COLUMN \"id\" DROP IDENTITY",
        ),
    ];
    for (change, expected) in cases {
        let statements = render_change(&change).expect("change renders");
        assert_eq!(statements, [expected], "for change: {change}");
    }
}

#[test]
fn primary_key_replacement_renders_drop_then_add() {
    let statements = render_change(&SchemaChange::SetPrimaryKey {
        table: TableName::qualified("public", "users"),
        from: vec!["id".to_owned()],
        to: vec!["id".to_owned(), "email".to_owned()],
    })
    .expect("primary-key change renders");
    assert_eq!(
        statements,
        [
            "ALTER TABLE \"public\".\"users\" DROP CONSTRAINT \"users_pkey\"",
            "ALTER TABLE \"public\".\"users\" ADD PRIMARY KEY (\"id\", \"email\")",
        ]
    );
}

#[test]
fn adding_a_first_primary_key_skips_the_drop() {
    let statements = render_change(&SchemaChange::SetPrimaryKey {
        table: TableName::new("logs"),
        from: Vec::new(),
        to: vec!["id".to_owned()],
    })
    .expect("primary-key addition renders");
    assert_eq!(
        statements,
        ["ALTER TABLE \"logs\" ADD PRIMARY KEY (\"id\")"]
    );
}

#[test]
fn same_schema_table_rename_is_one_statement() {
    let statements = render_change(&SchemaChange::RenameTable {
        from: TableName::qualified("public", "users"),
        to: TableName::qualified("public", "accounts"),
    })
    .expect("rename renders");
    assert_eq!(
        statements,
        ["ALTER TABLE \"public\".\"users\" RENAME TO \"accounts\""]
    );
}

#[test]
fn cross_schema_table_rename_adds_a_schema_move() {
    let statements = render_change(&SchemaChange::RenameTable {
        from: TableName::qualified("public", "users"),
        to: TableName::qualified("archive", "accounts"),
    })
    .expect("cross-schema rename renders");
    assert_eq!(
        statements,
        [
            "ALTER TABLE \"public\".\"users\" RENAME TO \"accounts\"",
            "ALTER TABLE \"public\".\"accounts\" SET SCHEMA \"archive\"",
        ]
    );
}

#[test]
fn change_sets_render_in_order() {
    let statements = render_changes(&[
        SchemaChange::CreateTable(
            TableDef::new(TableName::new("tags"))
                .with_column(ColumnDef::new("id", ColumnType::Int64))
                .with_primary_key(vec!["id".to_owned()]),
        ),
        SchemaChange::DropTable(TableName::new("legacy")),
    ])
    .expect("change set renders");
    assert_eq!(
        statements,
        [
            "CREATE TABLE \"tags\" (\"id\" bigint NOT NULL, PRIMARY KEY (\"id\"))",
            "DROP TABLE \"legacy\"",
        ]
    );
}

#[test]
fn foreign_key_changes_render_constraint_statements() {
    let posts = TableName::qualified("public", "posts");
    let add = SchemaChange::AddForeignKey {
        table: posts.clone(),
        foreign_key: ForeignKeyDef::new(
            "posts_author_id_fkey",
            "author_id",
            TableName::qualified("public", "users"),
            "id",
        )
        .on_delete(ReferentialAction::Cascade)
        .on_update(ReferentialAction::Restrict),
    };
    assert_eq!(
        render_change(&add).expect("add renders"),
        ["ALTER TABLE \"public\".\"posts\" \
          ADD CONSTRAINT \"posts_author_id_fkey\" \
          FOREIGN KEY (\"author_id\") REFERENCES \"public\".\"users\" (\"id\") \
          ON DELETE CASCADE ON UPDATE RESTRICT"]
    );

    // NO ACTION is the database default and stays unspelled, matching what
    // PostgreSQL itself prints for such a constraint.
    let plain = SchemaChange::AddForeignKey {
        table: posts.clone(),
        foreign_key: ForeignKeyDef::new(
            "posts_editor_id_fkey",
            "editor_id",
            TableName::qualified("public", "users"),
            "id",
        ),
    };
    assert_eq!(
        render_change(&plain).expect("add renders"),
        ["ALTER TABLE \"public\".\"posts\" \
          ADD CONSTRAINT \"posts_editor_id_fkey\" \
          FOREIGN KEY (\"editor_id\") REFERENCES \"public\".\"users\" (\"id\")"]
    );

    let drop = SchemaChange::DropForeignKey {
        table: posts,
        name: "posts_author_id_fkey".to_owned(),
    };
    assert_eq!(
        render_change(&drop).expect("drop renders"),
        ["ALTER TABLE \"public\".\"posts\" DROP CONSTRAINT \"posts_author_id_fkey\""]
    );
}

#[test]
fn hand_built_create_table_renders_inline_foreign_keys() {
    let table = TableDef::new(TableName::new("posts"))
        .with_column(ColumnDef::new("id", ColumnType::Int64))
        .with_column(ColumnDef::new("author_id", ColumnType::Int64))
        .with_primary_key(vec!["id".to_owned()])
        .with_foreign_key(
            ForeignKeyDef::new(
                "posts_author_id_fkey",
                "author_id",
                TableName::new("users"),
                "id",
            )
            .on_delete(ReferentialAction::SetNull),
        );
    assert_eq!(
        render_change(&SchemaChange::CreateTable(table)).expect("create renders"),
        ["CREATE TABLE \"posts\" (\
             \"author_id\" bigint NOT NULL, \
             \"id\" bigint NOT NULL, \
             PRIMARY KEY (\"id\"), \
             CONSTRAINT \"posts_author_id_fkey\" FOREIGN KEY (\"author_id\") \
             REFERENCES \"users\" (\"id\") ON DELETE SET NULL)"]
    );
}
