//! PostgreSQL DDL rendering for schema changes.
//!
//! Each [`SchemaChange`] renders as one or more complete statements.
//! Spelling decisions specific to this dialect:
//!
//! - Generated keys use `GENERATED BY DEFAULT AS IDENTITY` — the modern
//!   replacement for `serial` — with `BY DEFAULT` so fixtures and imports
//!   can still insert explicit values.
//! - Type changes always carry a `USING` cast, so conversions PostgreSQL
//!   cannot perform implicitly still render as valid statements.
//! - Constraint names follow PostgreSQL's own defaults (`{table}_pkey`,
//!   `{table}_{column}_key`), so constraints created inline by
//!   `CREATE TABLE` can later be dropped by the names PostgreSQL gave them.

use jetorm_entity::ColumnType;
use jetorm_schema::{ColumnDef, SchemaChange, TableDef, TableName};

use crate::error::RenderError;
use crate::postgres::quote_identifier;

/// Fractional-second digits used for every temporal column type; matches the
/// query lowering in `jetorm-query`.
const TEMPORAL_PRECISION: u8 = 6;

/// Renders one schema change as complete PostgreSQL statements.
///
/// Most changes render as exactly one statement; primary-key replacements
/// and cross-schema table renames need two.
///
/// # Errors
///
/// Returns an error when an identifier cannot be represented.
pub fn render_change(change: &SchemaChange) -> Result<Vec<String>, RenderError> {
    match change {
        SchemaChange::CreateTable(table) => Ok(vec![create_table_sql(table)?]),
        SchemaChange::DropTable(table) => Ok(vec![format!("DROP TABLE {}", table_sql(table)?)]),
        SchemaChange::RenameTable { from, to } => rename_table_sql(from, to),
        SchemaChange::AddColumn { table, column } => Ok(vec![format!(
            "ALTER TABLE {} ADD COLUMN {}",
            table_sql(table)?,
            column_sql(column)?
        )]),
        SchemaChange::DropColumn { table, column } => Ok(vec![format!(
            "ALTER TABLE {} DROP COLUMN {}",
            table_sql(table)?,
            quote_identifier(column)?
        )]),
        SchemaChange::RenameColumn { table, from, to } => Ok(vec![format!(
            "ALTER TABLE {} RENAME COLUMN {} TO {}",
            table_sql(table)?,
            quote_identifier(from)?,
            quote_identifier(to)?
        )]),
        SchemaChange::AlterColumnType {
            table, column, to, ..
        } => {
            let column = quote_identifier(column)?;
            let type_name = column_type_name(*to);
            Ok(vec![format!(
                "ALTER TABLE {} ALTER COLUMN {column} TYPE {type_name} \
                 USING {column}::{type_name}",
                table_sql(table)?
            )])
        }
        SchemaChange::SetNullable {
            table,
            column,
            nullable,
        } => Ok(vec![format!(
            "ALTER TABLE {} ALTER COLUMN {} {} NOT NULL",
            table_sql(table)?,
            quote_identifier(column)?,
            if *nullable { "DROP" } else { "SET" }
        )]),
        SchemaChange::SetUnique {
            table,
            column,
            unique,
        } => {
            let constraint = quote_identifier(&format!("{}_{column}_key", table.name()))?;
            Ok(vec![if *unique {
                format!(
                    "ALTER TABLE {} ADD CONSTRAINT {constraint} UNIQUE ({})",
                    table_sql(table)?,
                    quote_identifier(column)?
                )
            } else {
                format!(
                    "ALTER TABLE {} DROP CONSTRAINT {constraint}",
                    table_sql(table)?
                )
            }])
        }
        SchemaChange::SetAutoIncrement {
            table,
            column,
            auto_increment,
        } => Ok(vec![format!(
            "ALTER TABLE {} ALTER COLUMN {} {}",
            table_sql(table)?,
            quote_identifier(column)?,
            if *auto_increment {
                "ADD GENERATED BY DEFAULT AS IDENTITY"
            } else {
                "DROP IDENTITY"
            }
        )]),
        SchemaChange::SetPrimaryKey { table, from, to } => {
            let mut statements = Vec::with_capacity(2);
            if !from.is_empty() {
                statements.push(format!(
                    "ALTER TABLE {} DROP CONSTRAINT {}",
                    table_sql(table)?,
                    quote_identifier(&format!("{}_pkey", table.name()))?
                ));
            }
            if !to.is_empty() {
                statements.push(format!(
                    "ALTER TABLE {} ADD PRIMARY KEY ({})",
                    table_sql(table)?,
                    column_list(to)?
                ));
            }
            Ok(statements)
        }
    }
}

/// Renders every change of a change set in order.
///
/// # Errors
///
/// Returns the first rendering failure.
pub fn render_changes(changes: &[SchemaChange]) -> Result<Vec<String>, RenderError> {
    let mut statements = Vec::with_capacity(changes.len());
    for change in changes {
        statements.extend(render_change(change)?);
    }
    Ok(statements)
}

fn create_table_sql(table: &TableDef) -> Result<String, RenderError> {
    let mut items = Vec::new();
    for column in table.columns() {
        items.push(column_sql(column)?);
    }
    if !table.primary_key().is_empty() {
        items.push(format!(
            "PRIMARY KEY ({})",
            column_list(table.primary_key())?
        ));
    }
    Ok(format!(
        "CREATE TABLE {} ({})",
        table_sql(table.name())?,
        items.join(", ")
    ))
}

fn rename_table_sql(from: &TableName, to: &TableName) -> Result<Vec<String>, RenderError> {
    let mut statements = vec![format!(
        "ALTER TABLE {} RENAME TO {}",
        table_sql(from)?,
        quote_identifier(to.name())?
    )];
    // RENAME cannot move a table across schemas; that takes a second step.
    if from.schema() != to.schema() {
        let renamed = match from.schema() {
            Some(schema) => format!(
                "{}.{}",
                quote_identifier(schema)?,
                quote_identifier(to.name())?
            ),
            None => quote_identifier(to.name())?,
        };
        let target_schema = to.schema().ok_or_else(|| {
            RenderError::unsupported(
                "moving a table out of every schema requires an explicit target schema",
            )
        })?;
        statements.push(format!(
            "ALTER TABLE {renamed} SET SCHEMA {}",
            quote_identifier(target_schema)?
        ));
    }
    Ok(statements)
}

fn column_sql(column: &ColumnDef) -> Result<String, RenderError> {
    let mut sql = format!(
        "{} {}",
        quote_identifier(column.name())?,
        column_type_name(column.column_type())
    );
    if column.is_auto_increment() {
        sql.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if !column.is_nullable() {
        sql.push_str(" NOT NULL");
    }
    if column.is_unique() {
        sql.push_str(" UNIQUE");
    }
    Ok(sql)
}

fn table_sql(table: &TableName) -> Result<String, RenderError> {
    match table.schema() {
        Some(schema) => Ok(format!(
            "{}.{}",
            quote_identifier(schema)?,
            quote_identifier(table.name())?
        )),
        None => quote_identifier(table.name()),
    }
}

fn column_list(columns: &[String]) -> Result<String, RenderError> {
    let quoted: Vec<String> = columns
        .iter()
        .map(|column| quote_identifier(column))
        .collect::<Result<_, _>>()?;
    Ok(quoted.join(", "))
}

/// Returns the PostgreSQL type name for one entity column type.
fn column_type_name(column_type: ColumnType) -> String {
    match column_type {
        ColumnType::Boolean => "boolean".to_owned(),
        ColumnType::Int16 => "smallint".to_owned(),
        ColumnType::Int32 => "integer".to_owned(),
        ColumnType::Int64 => "bigint".to_owned(),
        ColumnType::Float32 => "real".to_owned(),
        ColumnType::Float64 => "double precision".to_owned(),
        ColumnType::Text => "text".to_owned(),
        ColumnType::Bytes => "bytea".to_owned(),
        ColumnType::Date => "date".to_owned(),
        ColumnType::Time => format!("time({TEMPORAL_PRECISION})"),
        ColumnType::Timestamp => format!("timestamp({TEMPORAL_PRECISION})"),
        ColumnType::TimestampUtc => format!("timestamptz({TEMPORAL_PRECISION})"),
        ColumnType::Uuid => "uuid".to_owned(),
        ColumnType::Json => "jsonb".to_owned(),
    }
}
