//! PostgreSQL DDL rendering for schema changes.
//!
//! Each [`SchemaChange`] renders as one or more complete statements.
//! Spelling decisions specific to this dialect:
//!
//! - Generated keys use `GENERATED BY DEFAULT AS IDENTITY` — the modern
//!   replacement for `serial` — with `BY DEFAULT` so fixtures and imports
//!   can still insert explicit values.
//! - Type changes always carry a `USING` cast, so conversions PostgreSQL
//!   cannot perform implicitly still render as valid statements.
//! - Constraint names follow PostgreSQL's own defaults (`{table}_pkey`,
//!   `{table}_{column}_key`), so constraints created inline by
//!   `CREATE TABLE` can later be dropped by the names PostgreSQL gave them.

use jetorm_entity::{ColumnType, ReferentialAction};
use jetorm_schema::{ColumnDef, ForeignKeyDef, SchemaChange, TableDef, TableName};

use crate::error::RenderError;
use crate::postgres::quote_identifier;
use crate::postgres::types::custom_type_name;

/// Fractional-second digits used for every temporal column type; matches the
/// query lowering in `jetorm-query`.
const TEMPORAL_PRECISION: u8 = 6;

/// Renders one schema change as complete PostgreSQL statements.
///
/// Most changes render as exactly one statement; primary-key replacements
/// and cross-schema table renames need two.
///
/// # Errors
///
/// Returns an error when an identifier cannot be represented.
pub fn render_change(change: &SchemaChange) -> Result<Vec<String>, RenderError> {
    match change {
        SchemaChange::CreateTable(table) => Ok(vec![create_table_sql(table)?]),
        SchemaChange::DropTable(table) => Ok(vec![format!("DROP TABLE {}", table_sql(table)?)]),
        SchemaChange::RenameTable { from, to } => rename_table_sql(from, to),
        SchemaChange::AddColumn { table, column } => Ok(vec![format!(
            "ALTER TABLE {} ADD COLUMN {}",
            table_sql(table)?,
            column_sql(column)?
        )]),
        SchemaChange::DropColumn { table, column } => Ok(vec![format!(
            "ALTER TABLE {} DROP COLUMN {}",
            table_sql(table)?,
            quote_identifier(column)?
        )]),
        SchemaChange::RenameColumn { table, from, to } => Ok(vec![format!(
            "ALTER TABLE {} RENAME COLUMN {} TO {}",
            table_sql(table)?,
            quote_identifier(from)?,
            quote_identifier(to)?
        )]),
        SchemaChange::AlterColumnType {
            table,
            column,
            to,
            from_type_name,
            to_type_name,
            ..
        } => {
            let column = quote_identifier(column)?;
            let type_name = match to_type_name {
                Some(name) => custom_type_name(name)?,
                None => column_type_name(*to),
            };
            // A named type on either side routes the cast through text:
            // two enums have no direct cast between them, and text is the
            // representation every enum casts to and from. Values outside
            // the target's labels fail at apply time — honestly.
            let cast = if from_type_name.is_some() || to_type_name.is_some() {
                format!("{column}::text::{type_name}")
            } else {
                format!("{column}::{type_name}")
            };
            Ok(vec![format!(
                "ALTER TABLE {} ALTER COLUMN {column} TYPE {type_name} \
                 USING {cast}",
                table_sql(table)?
            )])
        }
        SchemaChange::SetNullable {
            table,
            column,
            nullable,
        } => Ok(vec![format!(
            "ALTER TABLE {} ALTER COLUMN {} {} NOT NULL",
            table_sql(table)?,
            quote_identifier(column)?,
            if *nullable { "DROP" } else { "SET" }
        )]),
        SchemaChange::SetUnique {
            table,
            column,
            unique,
        } => {
            let constraint = quote_identifier(&format!("{}_{column}_key", table.name()))?;
            Ok(vec![if *unique {
                format!(
                    "ALTER TABLE {} ADD CONSTRAINT {constraint} UNIQUE ({})",
                    table_sql(table)?,
                    quote_identifier(column)?
                )
            } else {
                format!(
                    "ALTER TABLE {} DROP CONSTRAINT {constraint}",
                    table_sql(table)?
                )
            }])
        }
        SchemaChange::SetAutoIncrement {
            table,
            column,
            auto_increment,
        } => Ok(vec![format!(
            "ALTER TABLE {} ALTER COLUMN {} {}",
            table_sql(table)?,
            quote_identifier(column)?,
            if *auto_increment {
                "ADD GENERATED BY DEFAULT AS IDENTITY"
            } else {
                "DROP IDENTITY"
            }
        )]),
        SchemaChange::SetPrimaryKey { table, from, to } => {
            let mut statements = Vec::with_capacity(2);
            if !from.is_empty() {
                statements.push(format!(
                    "ALTER TABLE {} DROP CONSTRAINT {}",
                    table_sql(table)?,
                    quote_identifier(&format!("{}_pkey", table.name()))?
                ));
            }
            if !to.is_empty() {
                statements.push(format!(
                    "ALTER TABLE {} ADD PRIMARY KEY ({})",
                    table_sql(table)?,
                    column_list(to)?
                ));
            }
            Ok(statements)
        }
        SchemaChange::AddForeignKey { table, foreign_key } => {
            Ok(vec![add_foreign_key_sql(table, foreign_key)?])
        }
        SchemaChange::DropForeignKey { table, name } => Ok(vec![format!(
            "ALTER TABLE {} DROP CONSTRAINT {}",
            table_sql(table)?,
            quote_identifier(name)?
        )]),
        SchemaChange::CreateEnum { name, variants } => {
            let mut spelled = Vec::with_capacity(variants.len());
            for variant in variants {
                spelled.push(quote_literal(variant));
            }
            Ok(vec![format!(
                "CREATE TYPE {} AS ENUM ({})",
                custom_type_name(name)?,
                spelled.join(", ")
            )])
        }
        SchemaChange::AddEnumVariant { name, variant } => Ok(vec![format!(
            "ALTER TYPE {} ADD VALUE {}",
            custom_type_name(name)?,
            quote_literal(variant)
        )]),
        SchemaChange::DropEnum { name } => {
            Ok(vec![format!("DROP TYPE {}", custom_type_name(name)?)])
        }
    }
}

fn add_foreign_key_sql(
    table: &TableName,
    foreign_key: &ForeignKeyDef,
) -> Result<String, RenderError> {
    Ok(format!(
        "ALTER TABLE {} ADD {}",
        table_sql(table)?,
        foreign_key_clause(foreign_key)?
    ))
}

fn foreign_key_clause(foreign_key: &ForeignKeyDef) -> Result<String, RenderError> {
    let mut sql = format!(
        "CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
        quote_identifier(foreign_key.name())?,
        quote_identifier(foreign_key.column())?,
        table_sql(foreign_key.target_table())?,
        quote_identifier(foreign_key.target_column())?
    );
    if let Some(action) = referential_action_sql(foreign_key.delete_action())? {
        sql.push_str(" ON DELETE ");
        sql.push_str(action);
    }
    if let Some(action) = referential_action_sql(foreign_key.update_action())? {
        sql.push_str(" ON UPDATE ");
        sql.push_str(action);
    }
    Ok(sql)
}

/// Returns the action clause, or `None` for `NO ACTION` — the default the
/// database assumes when the clause is absent, kept absent so rendered DDL
/// matches what PostgreSQL itself prints.
fn referential_action_sql(action: ReferentialAction) -> Result<Option<&'static str>, RenderError> {
    match action {
        ReferentialAction::NoAction => Ok(None),
        ReferentialAction::Restrict => Ok(Some("RESTRICT")),
        ReferentialAction::Cascade => Ok(Some("CASCADE")),
        ReferentialAction::SetNull => Ok(Some("SET NULL")),
        ReferentialAction::SetDefault => Ok(Some("SET DEFAULT")),
        // `ReferentialAction` is non-exhaustive: fail loudly when a variant
        // this dialect has not learned appears, instead of rendering a
        // constraint with silently wrong semantics.
        _ => Err(RenderError::unsupported(
            "referential action not supported by the PostgreSQL renderer",
        )),
    }
}

/// Statements of one change, split by when they can safely run.
///
/// Staging exists for one reason: adding a foreign key to a populated
/// table scans it under a lock strong enough to stall writes. The staged
/// form adds the constraint `NOT VALID` — enforced for new writes
/// immediately, cheap to take — and validates existing rows afterwards,
/// outside the migration's transaction, under a weaker lock.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StagedStatements {
    /// Statements that run inside the migration's transaction.
    pub immediate: Vec<String>,
    /// Validations that run afterwards, each in its own transaction.
    pub deferred: Vec<String>,
}

/// Renders one change with foreign-key additions staged.
///
/// Every change except [`SchemaChange::AddForeignKey`] renders exactly as
/// [`render_change`] does, entirely immediate.
///
/// # Errors
///
/// Returns an error when an identifier cannot be represented.
pub fn render_change_staged(change: &SchemaChange) -> Result<StagedStatements, RenderError> {
    if let SchemaChange::AddForeignKey { table, foreign_key } = change {
        return Ok(StagedStatements {
            immediate: vec![format!(
                "{} NOT VALID",
                add_foreign_key_sql(table, foreign_key)?
            )],
            deferred: vec![format!(
                "ALTER TABLE {} VALIDATE CONSTRAINT {}",
                table_sql(table)?,
                quote_identifier(foreign_key.name())?
            )],
        });
    }
    Ok(StagedStatements {
        immediate: render_change(change)?,
        deferred: Vec::new(),
    })
}

/// Renders every change of a change set in order.
///
/// # Errors
///
/// Returns the first rendering failure.
pub fn render_changes(changes: &[SchemaChange]) -> Result<Vec<String>, RenderError> {
    let mut statements = Vec::with_capacity(changes.len());
    for change in changes {
        statements.extend(render_change(change)?);
    }
    Ok(statements)
}

fn create_table_sql(table: &TableDef) -> Result<String, RenderError> {
    let mut items = Vec::new();
    for column in table.columns() {
        items.push(column_sql(column)?);
    }
    if !table.primary_key().is_empty() {
        items.push(format!(
            "PRIMARY KEY ({})",
            column_list(table.primary_key())?
        ));
    }
    // Diff-produced creates carry no constraints (they land as separate
    // `AddForeignKey` changes once every referenced table exists), but a
    // hand-built definition renders faithfully.
    for foreign_key in table.foreign_keys() {
        items.push(foreign_key_clause(foreign_key)?);
    }
    Ok(format!(
        "CREATE TABLE {} ({})",
        table_sql(table.name())?,
        items.join(", ")
    ))
}

fn rename_table_sql(from: &TableName, to: &TableName) -> Result<Vec<String>, RenderError> {
    let mut statements = vec![format!(
        "ALTER TABLE {} RENAME TO {}",
        table_sql(from)?,
        quote_identifier(to.name())?
    )];
    // RENAME cannot move a table across schemas; that takes a second step.
    if from.schema() != to.schema() {
        let renamed = match from.schema() {
            Some(schema) => format!(
                "{}.{}",
                quote_identifier(schema)?,
                quote_identifier(to.name())?
            ),
            None => quote_identifier(to.name())?,
        };
        let target_schema = to.schema().ok_or_else(|| {
            RenderError::unsupported(
                "moving a table out of every schema requires an explicit target schema",
            )
        })?;
        statements.push(format!(
            "ALTER TABLE {renamed} SET SCHEMA {}",
            quote_identifier(target_schema)?
        ));
    }
    Ok(statements)
}

/// Quotes one string literal, doubling embedded quotes.
fn quote_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn column_sql(column: &ColumnDef) -> Result<String, RenderError> {
    // A named type overrides the dialect's spelling of the column type —
    // this is how native enum columns take their `CREATE TYPE`d type.
    let type_sql = match column.type_name() {
        Some(name) => custom_type_name(name)?,
        None => column_type_name(column.column_type()),
    };
    let mut sql = format!("{} {}", quote_identifier(column.name())?, type_sql);
    if column.is_auto_increment() {
        sql.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if !column.is_nullable() {
        sql.push_str(" NOT NULL");
    }
    if column.is_unique() {
        sql.push_str(" UNIQUE");
    }
    Ok(sql)
}

fn table_sql(table: &TableName) -> Result<String, RenderError> {
    match table.schema() {
        Some(schema) => Ok(format!(
            "{}.{}",
            quote_identifier(schema)?,
            quote_identifier(table.name())?
        )),
        None => quote_identifier(table.name()),
    }
}

fn column_list(columns: &[String]) -> Result<String, RenderError> {
    let quoted: Vec<String> = columns
        .iter()
        .map(|column| quote_identifier(column))
        .collect::<Result<_, _>>()?;
    Ok(quoted.join(", "))
}

/// Returns the PostgreSQL type name for one entity column type.
fn column_type_name(column_type: ColumnType) -> String {
    match column_type {
        ColumnType::Boolean => "boolean".to_owned(),
        ColumnType::Int16 => "smallint".to_owned(),
        ColumnType::Int32 => "integer".to_owned(),
        ColumnType::Int64 => "bigint".to_owned(),
        ColumnType::Float32 => "real".to_owned(),
        ColumnType::Float64 => "double precision".to_owned(),
        ColumnType::Decimal => "numeric".to_owned(),
        ColumnType::Text => "text".to_owned(),
        ColumnType::Bytes => "bytea".to_owned(),
        ColumnType::Date => "date".to_owned(),
        ColumnType::Time => format!("time({TEMPORAL_PRECISION})"),
        ColumnType::Timestamp => format!("timestamp({TEMPORAL_PRECISION})"),
        ColumnType::TimestampUtc => format!("timestamptz({TEMPORAL_PRECISION})"),
        ColumnType::Uuid => "uuid".to_owned(),
        ColumnType::Json => "jsonb".to_owned(),
        ColumnType::ArrayOf(element) => {
            format!("{}[]", column_type_name(element.as_column_type()))
        }
    }
}
