//! Entity code generation from an introspected schema.
//!
//! `jet db pull` turns a [`SchemaSet`] into a Rust module of `JetModel`
//! structs. The mapping is deliberately predictable rather than clever:
//! table `users` becomes struct `Users` with column module `users`, and a
//! `_id` column with a single-column foreign key becomes a
//! `#[jet(references = ...)]` attribute whose relation name falls out of
//! the derive's own `_id`-stripping convention.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use jetorm_entity::{ColumnType, ReferentialAction};
use jetorm_schema::{ColumnDef, SchemaSet, TableDef};

/// Keywords that must be spelled `r#name` to be used as a field name.
const RAW_ONLY_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do", "dyn",
    "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let",
    "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
    "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe", "unsized", "use",
    "virtual", "where", "while", "yield",
];

/// Names no identifier — raw or otherwise — may take.
const RESERVED_NAMES: &[&str] = &["self", "Self", "super", "crate"];

/// Generated entity source plus everything worth telling the operator.
pub struct GeneratedEntities {
    /// The Rust source of the module.
    pub source: String,
    /// Facts the generation had to bend — renamed fields, dropped flags.
    pub warnings: Vec<String>,
}

/// Renders one schema as a self-contained Rust source file.
#[must_use]
pub fn entities_source(schema: &SchemaSet) -> GeneratedEntities {
    let mut source = String::from(
        "//! Entities generated by `jet db pull`.\n//!\n//! Regenerate rather than edit: \
         schema changes belong in migrations,\n//! and this file mirrors the database.\n\n\
         use jetorm::prelude::*;\n",
    );
    let mut warnings = Vec::new();
    for table in schema.tables() {
        source.push('\n');
        write_table(&mut source, schema, table, &mut warnings);
    }
    GeneratedEntities { source, warnings }
}

fn write_table(
    source: &mut String,
    schema: &SchemaSet,
    table: &TableDef,
    warnings: &mut Vec<String>,
) {
    let struct_name = pascal_case(table.name().name());
    let _ = writeln!(source, "/// Row of `{}`.", table.name());
    let _ = writeln!(source, "#[derive(Clone, Debug, PartialEq, JetModel)]");
    match table.name().schema() {
        Some(qualifier) => {
            let _ = writeln!(
                source,
                "#[jet(table = \"{}\", schema = \"{qualifier}\")]",
                table.name().name()
            );
        }
        None => {
            let _ = writeln!(source, "#[jet(table = \"{}\")]", table.name().name());
        }
    }
    let _ = writeln!(source, "pub struct {struct_name} {{");
    // Every column marker the derive will claim; relation names colliding
    // with one must take an explicit spelling or the derive errors.
    let claimed_markers: BTreeSet<String> = table
        .columns()
        .map(|column| pascal_case(column.name()))
        .collect();
    for column in table.columns() {
        write_column(source, schema, table, column, &claimed_markers, warnings);
    }
    source.push_str("}\n");
}

fn write_column(
    source: &mut String,
    schema: &SchemaSet,
    table: &TableDef,
    column: &ColumnDef,
    claimed_markers: &BTreeSet<String>,
    warnings: &mut Vec<String>,
) {
    let mut attributes = Vec::new();
    let is_key_member = table.primary_key().iter().any(|key| key == column.name());
    if is_key_member {
        if column.is_auto_increment() {
            attributes.push("primary_key, auto_increment".to_owned());
        } else {
            attributes.push("primary_key".to_owned());
        }
    } else if column.is_auto_increment() {
        // The derive ties database-generated values to key membership; a
        // non-key identity column cannot carry the flag yet.
        warnings.push(format!(
            "{}.{}: identity on a non-key column is not representable; \
             the generated entity omits auto_increment",
            table.name(),
            column.name()
        ));
    }
    if column.is_unique() {
        attributes.push("unique".to_owned());
    }
    for foreign_key in table.foreign_keys() {
        if foreign_key.column() != column.name() {
            continue;
        }
        // The referenced marker lives in the referenced table's generated
        // module; the referenced table must be part of this same pull.
        if schema.table(foreign_key.target_table()).is_none() {
            continue;
        }
        let module = snake_case(foreign_key.target_table().name());
        let marker = pascal_case(foreign_key.target_column());
        let mut reference = format!("references = \"{module}::{marker}\"");
        // The derive's default relation name strips `_id`; when that name's
        // marker collides with a column's — a table with both `author` and
        // `author_id` — the derive would error, so spell one explicitly.
        let default_relation = column
            .name()
            .strip_suffix("_id")
            .filter(|stem| !stem.is_empty());
        match default_relation {
            Some(stem) if !claimed_markers.contains(&pascal_case(stem)) => {}
            _ => {
                let _ = write!(reference, ", relation = \"{}_rel\"", column.name());
            }
        }
        for (clause, action) in [
            ("on_delete", foreign_key.delete_action()),
            ("on_update", foreign_key.update_action()),
        ] {
            if let Some(name) = action_attribute(action) {
                let _ = write!(reference, ", {clause} = \"{name}\"");
            }
        }
        attributes.push(reference);
    }

    // Field spelling: keywords escape as raw identifiers; the four names
    // Rust reserves outright get a synthetic field mapped back onto the
    // column through the derive's own column attribute.
    let field_name = if RESERVED_NAMES.contains(&column.name()) {
        attributes.push(format!("column = \"{}\"", column.name()));
        format!("{}_field", column.name().to_lowercase())
    } else if RAW_ONLY_KEYWORDS.contains(&column.name()) {
        format!("r#{}", column.name())
    } else {
        column.name().to_owned()
    };

    for attribute in &attributes {
        let _ = writeln!(source, "    #[jet({attribute})]");
    }
    let rust_type = field_type_of(column.column_type());
    let field_type = if column.is_nullable() {
        format!("Option<{rust_type}>")
    } else {
        rust_type
    };
    let _ = writeln!(source, "    pub {field_name}: {field_type},");
}

const fn action_attribute(action: ReferentialAction) -> Option<&'static str> {
    match action {
        ReferentialAction::NoAction => None,
        ReferentialAction::Restrict => Some("restrict"),
        ReferentialAction::Cascade => Some("cascade"),
        ReferentialAction::SetNull => Some("set_null"),
        ReferentialAction::SetDefault => Some("set_default"),
        _ => None,
    }
}

fn field_type_of(column_type: ColumnType) -> String {
    if let ColumnType::ArrayOf(element) = column_type {
        return format!("Vec<{}>", rust_type_of(element.as_column_type()));
    }
    rust_type_of(column_type).to_owned()
}

const fn rust_type_of(column_type: ColumnType) -> &'static str {
    match column_type {
        ColumnType::Boolean => "bool",
        ColumnType::Int16 => "i16",
        ColumnType::Int32 => "i32",
        ColumnType::Int64 => "i64",
        ColumnType::Float32 => "f32",
        ColumnType::Float64 => "f64",
        ColumnType::Decimal => "rust_decimal::Decimal",
        ColumnType::Text => "String",
        ColumnType::Bytes => "Vec<u8>",
        ColumnType::Date => "chrono::NaiveDate",
        ColumnType::Time => "chrono::NaiveTime",
        ColumnType::Timestamp => "chrono::NaiveDateTime",
        ColumnType::TimestampUtc => "chrono::DateTime<chrono::Utc>",
        ColumnType::Uuid => "uuid::Uuid",
        ColumnType::Json => "serde_json::Value",
        // Reached only through scalar element mapping; arrays route
        // through field_type_of.
        ColumnType::ArrayOf(_) => "unreachable",
    }
}

fn pascal_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    let mut upper_next = true;
    for character in input.chars() {
        if character == '_' {
            upper_next = true;
        } else if upper_next {
            output.extend(character.to_uppercase());
            upper_next = false;
        } else {
            output.push(character);
        }
    }
    output
}

fn snake_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len() + 4);
    for (index, character) in input.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                output.push('_');
            }
            output.extend(character.to_lowercase());
        } else {
            output.push(character);
        }
    }
    output
}
