//! Entity code generation from an introspected schema.
//!
//! `jet db pull` turns a [`SchemaSet`] into a Rust module of `JetModel`
//! structs. The mapping is deliberately predictable rather than clever:
//! table `users` becomes struct `Users` with column module `users`, and a
//! `_id` column with a single-column foreign key becomes a
//! `#[jet(references = ...)]` attribute whose relation name falls out of
//! the derive's own `_id`-stripping convention.

use std::fmt::Write as _;

use jetorm_entity::{ColumnType, ReferentialAction};
use jetorm_schema::{ColumnDef, SchemaSet, TableDef};

/// Renders one schema as a self-contained Rust source file.
#[must_use]
pub fn entities_source(schema: &SchemaSet) -> String {
    let mut source = String::from(
        "//! Entities generated by `jet db pull`.\n//!\n//! Regenerate rather than edit: \
         schema changes belong in migrations,\n//! and this file mirrors the database.\n\n\
         use jetorm::prelude::*;\n",
    );
    for table in schema.tables() {
        source.push('\n');
        write_table(&mut source, schema, table);
    }
    source
}

fn write_table(source: &mut String, schema: &SchemaSet, table: &TableDef) {
    let struct_name = pascal_case(table.name().name());
    let _ = writeln!(source, "/// Row of `{}`.", table.name());
    let _ = writeln!(source, "#[derive(Clone, Debug, PartialEq, JetModel)]");
    match table.name().schema() {
        Some(qualifier) => {
            let _ = writeln!(
                source,
                "#[jet(table = \"{}\", schema = \"{qualifier}\")]",
                table.name().name()
            );
        }
        None => {
            let _ = writeln!(source, "#[jet(table = \"{}\")]", table.name().name());
        }
    }
    let _ = writeln!(source, "pub struct {struct_name} {{");
    for column in table.columns() {
        write_column(source, schema, table, column);
    }
    source.push_str("}\n");
}

fn write_column(source: &mut String, schema: &SchemaSet, table: &TableDef, column: &ColumnDef) {
    let mut attributes = Vec::new();
    if table.primary_key() == [column.name().to_owned()] {
        if column.is_auto_increment() {
            attributes.push("primary_key, auto_increment".to_owned());
        } else {
            attributes.push("primary_key".to_owned());
        }
    }
    if column.is_unique() {
        attributes.push("unique".to_owned());
    }
    for foreign_key in table.foreign_keys() {
        if foreign_key.column() != column.name() {
            continue;
        }
        // The referenced marker lives in the referenced table's generated
        // module; the referenced table must be part of this same pull.
        if schema.table(foreign_key.target_table()).is_none() {
            continue;
        }
        let module = snake_case(foreign_key.target_table().name());
        let marker = pascal_case(foreign_key.target_column());
        let mut reference = format!("references = \"{module}::{marker}\"");
        if column.name().strip_suffix("_id").is_none_or(str::is_empty) {
            let _ = write!(reference, ", relation = \"{}_ref\"", column.name());
        }
        for (clause, action) in [
            ("on_delete", foreign_key.delete_action()),
            ("on_update", foreign_key.update_action()),
        ] {
            if let Some(name) = action_attribute(action) {
                let _ = write!(reference, ", {clause} = \"{name}\"");
            }
        }
        attributes.push(reference);
    }

    for attribute in &attributes {
        let _ = writeln!(source, "    #[jet({attribute})]");
    }
    let rust_type = rust_type_of(column.column_type());
    let field_type = if column.is_nullable() {
        format!("Option<{rust_type}>")
    } else {
        rust_type.to_owned()
    };
    let _ = writeln!(source, "    pub {}: {field_type},", column.name());
}

const fn action_attribute(action: ReferentialAction) -> Option<&'static str> {
    match action {
        ReferentialAction::NoAction => None,
        ReferentialAction::Restrict => Some("restrict"),
        ReferentialAction::Cascade => Some("cascade"),
        ReferentialAction::SetNull => Some("set_null"),
        ReferentialAction::SetDefault => Some("set_default"),
        _ => None,
    }
}

const fn rust_type_of(column_type: ColumnType) -> &'static str {
    match column_type {
        ColumnType::Boolean => "bool",
        ColumnType::Int16 => "i16",
        ColumnType::Int32 => "i32",
        ColumnType::Int64 => "i64",
        ColumnType::Float32 => "f32",
        ColumnType::Float64 => "f64",
        ColumnType::Decimal => "rust_decimal::Decimal",
        ColumnType::Text => "String",
        ColumnType::Bytes => "Vec<u8>",
        ColumnType::Date => "chrono::NaiveDate",
        ColumnType::Time => "chrono::NaiveTime",
        ColumnType::Timestamp => "chrono::NaiveDateTime",
        ColumnType::TimestampUtc => "chrono::DateTime<chrono::Utc>",
        ColumnType::Uuid => "uuid::Uuid",
        ColumnType::Json => "serde_json::Value",
    }
}

fn pascal_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    let mut upper_next = true;
    for character in input.chars() {
        if character == '_' {
            upper_next = true;
        } else if upper_next {
            output.extend(character.to_uppercase());
            upper_next = false;
        } else {
            output.push(character);
        }
    }
    output
}

fn snake_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len() + 4);
    for (index, character) in input.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                output.push('_');
            }
            output.extend(character.to_lowercase());
        } else {
            output.push(character);
        }
    }
    output
}
