//! Entity code generation from an introspected schema.
//!
//! `jet db pull` turns a [`SchemaSet`] into a Rust module of `JetModel`
//! structs. The mapping is deliberately predictable rather than clever:
//! table `users` becomes struct `Users` with column module `users`, and a
//! `_id` column with a single-column foreign key becomes a
//! `#[jet(references = ...)]` attribute whose relation name falls out of
//! the derive's own `_id`-stripping convention.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use jetorm_entity::{ColumnType, ReferentialAction};
use jetorm_schema::{ColumnDef, SchemaSet, TableDef};

/// Keywords that must be spelled `r#name` to be used as a field name.
const RAW_ONLY_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do", "dyn",
    "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let",
    "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
    "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe", "unsized", "use",
    "virtual", "where", "while", "yield",
];

/// Names no identifier — raw or otherwise — may take.
const RESERVED_NAMES: &[&str] = &["self", "Self", "super", "crate"];

/// Prelude names the generated module itself uses in field types. A
/// generated type taking one of these would shadow it for every other
/// field in the module — `pub enum String` silently retypes every text
/// column — so they are claimed from the start.
const PRELUDE_NAMES: &[&str] = &[
    "String", "Vec", "Option", "Box", "Result", "Some", "None", "Ok", "Err", "Json",
];

/// Renders text as the body of a Rust string literal.
///
/// Database names and enum labels legally contain quotes, backslashes,
/// and control characters; interpolated verbatim they break out of the
/// literal — at best a compile error in the generated file, at worst
/// injected code. `escape_default` round-trips exactly: the escaped
/// literal decodes back to the original text.
fn string_literal(text: &str) -> String {
    text.chars().flat_map(char::escape_default).collect()
}

/// Renders text safe for a single-line doc comment.
///
/// A newline in a name would end the comment and leave the rest of the
/// name as bare tokens in the module.
fn doc_text(text: &str) -> String {
    text.chars()
        .map(|character| {
            if character.is_control() {
                ' '
            } else {
                character
            }
        })
        .collect()
}

/// Generated entity source plus everything worth telling the operator.
pub struct GeneratedEntities {
    /// The Rust source of the module.
    pub source: String,
    /// Facts the generation had to bend — renamed fields, dropped flags.
    pub warnings: Vec<String>,
}

/// Renders one schema as a self-contained Rust source file.
#[must_use]
pub fn entities_source(schema: &SchemaSet) -> GeneratedEntities {
    let mut source = String::from(
        "//! Entities generated by `jet db pull`.\n//!\n//! Regenerate rather than edit: \
         schema changes belong in migrations,\n//! and this file mirrors the database.\n\n\
         use jetorm::prelude::*;\n",
    );
    let mut warnings = Vec::new();
    let enum_types = write_enums(&mut source, schema, &mut warnings);
    // Two tables whose names case identically — `user_role` and a quoted
    // `"user-role"` — must not define the same struct twice; enum names
    // are claimed too, since write_enums already resolved against tables.
    let mut claimed: BTreeSet<String> = enum_types.values().cloned().collect();
    for table in schema.tables() {
        let mut struct_name = pascal_case(table.name().name());
        if !claimed.insert(struct_name.clone()) {
            let base = struct_name.clone();
            while !claimed.insert(struct_name.clone()) {
                struct_name.push_str("Table");
            }
            warnings.push(format!(
                "table `{}`: struct name {base:?} is already taken; \
                 generated as {struct_name:?}",
                table.name()
            ));
        }
        source.push('\n');
        write_table(
            &mut source,
            schema,
            table,
            &struct_name,
            &enum_types,
            &mut warnings,
        );
    }
    GeneratedEntities { source, warnings }
}

/// Renders every native enum type as a `JetEnum` and returns the mapping
/// from database type name to generated Rust type name.
///
/// An enum whose labels cannot become distinct Rust identifiers is skipped
/// with a warning, and so are its columns: a plain `String` field on an
/// enum-typed column would neither bind nor decode.
fn write_enums(
    source: &mut String,
    schema: &SchemaSet,
    warnings: &mut Vec<String>,
) -> std::collections::BTreeMap<String, String> {
    // Struct names are claimed by tables, and the prelude names the module
    // itself relies on are claimed from the start; an enum type cased like
    // any of them must take a distinct spelling.
    let mut claimed: BTreeSet<String> = schema
        .tables()
        .map(|table| pascal_case(table.name().name()))
        .chain(PRELUDE_NAMES.iter().map(ToString::to_string))
        .collect();
    let mut enum_types = std::collections::BTreeMap::new();
    for (name, variants) in schema.enums() {
        // A qualified type — `app.post_status` from a non-public pull —
        // takes its Rust name from the type itself, not the namespace.
        let bare = name.rsplit('.').next().unwrap_or(name);
        let mut rust_name = pascal_case(bare);
        if !valid_identifier(&rust_name) {
            warnings.push(format!(
                "enum type {name:?} has no Rust spelling; its columns are \
                 skipped until it gets one"
            ));
            continue;
        }
        // Suffix until the name is genuinely free — the first suffixed
        // spelling can itself be claimed by a table or an earlier enum.
        while claimed.contains(&rust_name) {
            rust_name.push_str("Enum");
        }
        let mut idents = Vec::with_capacity(variants.len());
        let mut seen = BTreeSet::new();
        for label in variants {
            let ident = pascal_case(label);
            if !valid_identifier(&ident) || !seen.insert(ident.clone()) {
                warnings.push(format!(
                    "enum type {name:?}: label {label:?} has no distinct Rust \
                     spelling; the type's columns are skipped until it gets one"
                ));
                idents.clear();
                break;
            }
            idents.push(ident);
        }
        if idents.is_empty() {
            continue;
        }
        claimed.insert(rust_name.clone());
        source.push('\n');
        let _ = writeln!(source, "/// Values of the `{}` enum type.", doc_text(name));
        let _ = writeln!(
            source,
            "#[derive(Clone, Copy, Debug, PartialEq, Eq, JetEnum)]"
        );
        let _ = writeln!(source, "#[jet(native = \"{}\")]", string_literal(name));
        let _ = writeln!(source, "pub enum {rust_name} {{");
        for (label, ident) in variants.iter().zip(&idents) {
            // The derive stores the snake_case of the variant name; a label
            // that spelling would not reproduce keeps its exact text.
            if snake_case(ident) != *label {
                let _ = writeln!(source, "    #[jet(rename = \"{}\")]", string_literal(label));
            }
            let _ = writeln!(source, "    {ident},");
        }
        source.push_str("}\n");
        enum_types.insert(name.to_owned(), rust_name);
    }
    enum_types
}

/// Whether the generated name is usable as a Rust identifier.
///
/// Rust identifiers follow Unicode XID, which is narrower than
/// alphanumeric — superscripts and vulgar fractions count as alphanumeric
/// but no identifier may hold them.
fn valid_identifier(name: &str) -> bool {
    let mut characters = name.chars();
    characters
        .next()
        .is_some_and(|first| unicode_ident::is_xid_start(first) || first == '_')
        && characters.all(unicode_ident::is_xid_continue)
        && !RAW_ONLY_KEYWORDS.contains(&name)
        && !RESERVED_NAMES.contains(&name)
}

fn write_table(
    source: &mut String,
    schema: &SchemaSet,
    table: &TableDef,
    struct_name: &str,
    enum_types: &std::collections::BTreeMap<String, String>,
    warnings: &mut Vec<String>,
) {
    let _ = writeln!(
        source,
        "/// Row of `{}`.",
        doc_text(&table.name().to_string())
    );
    let _ = writeln!(source, "#[derive(Clone, Debug, PartialEq, JetModel)]");
    match table.name().schema() {
        Some(qualifier) => {
            let _ = writeln!(
                source,
                "#[jet(table = \"{}\", schema = \"{}\")]",
                string_literal(table.name().name()),
                string_literal(qualifier)
            );
        }
        None => {
            let _ = writeln!(
                source,
                "#[jet(table = \"{}\")]",
                string_literal(table.name().name())
            );
        }
    }
    let _ = writeln!(source, "pub struct {struct_name} {{");
    // Every column marker the derive will claim; relation names colliding
    // with one must take an explicit spelling or the derive errors.
    let claimed_markers: BTreeSet<String> = table
        .columns()
        .map(|column| pascal_case(column.name()))
        .collect();
    for column in table.columns() {
        write_column(
            source,
            schema,
            table,
            column,
            &claimed_markers,
            enum_types,
            warnings,
        );
    }
    source.push_str("}\n");
}

#[allow(clippy::too_many_arguments)]
fn write_column(
    source: &mut String,
    schema: &SchemaSet,
    table: &TableDef,
    column: &ColumnDef,
    claimed_markers: &BTreeSet<String>,
    enum_types: &std::collections::BTreeMap<String, String>,
    warnings: &mut Vec<String>,
) {
    // A column of an enum type that got no Rust spelling cannot be
    // represented: a plain String field would neither bind (the insert
    // casts ::text against the enum column) nor decode (the driver
    // reports the enum's own type). Skip it and say so — the same
    // contract unmappable database types follow.
    let rust_type = match column.type_name() {
        Some(type_name) => match enum_types.get(type_name) {
            Some(enum_type) => enum_type.clone(),
            None => {
                warnings.push(format!(
                    "{}.{}: enum type {type_name:?} was not generated; the \
                     column is omitted from the entity until its labels get \
                     Rust spellings",
                    table.name(),
                    column.name()
                ));
                return;
            }
        },
        None => field_type_of(column.column_type()),
    };

    let mut attributes = Vec::new();
    let is_key_member = table.primary_key().iter().any(|key| key == column.name());
    if is_key_member {
        if column.is_auto_increment() {
            attributes.push("primary_key, auto_increment".to_owned());
        } else {
            attributes.push("primary_key".to_owned());
        }
    } else if column.is_auto_increment() {
        // The derive ties database-generated values to key membership; a
        // non-key identity column cannot carry the flag yet.
        warnings.push(format!(
            "{}.{}: identity on a non-key column is not representable; \
             the generated entity omits auto_increment",
            table.name(),
            column.name()
        ));
    }
    if column.is_unique() {
        attributes.push("unique".to_owned());
    }
    for foreign_key in table.foreign_keys() {
        if foreign_key.column() != column.name() {
            continue;
        }
        // The referenced marker lives in the referenced table's generated
        // module; the referenced table must be part of this same pull.
        if schema.table(foreign_key.target_table()).is_none() {
            continue;
        }
        let module = snake_case(foreign_key.target_table().name());
        let marker = pascal_case(foreign_key.target_column());
        let mut reference = format!("references = \"{module}::{marker}\"");
        // The derive's default relation name strips `_id`; when that name's
        // marker collides with a column's — a table with both `author` and
        // `author_id` — the derive would error, so spell one explicitly.
        let default_relation = column
            .name()
            .strip_suffix("_id")
            .filter(|stem| !stem.is_empty());
        match default_relation {
            Some(stem) if !claimed_markers.contains(&pascal_case(stem)) => {}
            _ => {
                let _ = write!(reference, ", relation = \"{}_rel\"", column.name());
            }
        }
        for (clause, action) in [
            ("on_delete", foreign_key.delete_action()),
            ("on_update", foreign_key.update_action()),
        ] {
            if let Some(name) = action_attribute(action) {
                let _ = write!(reference, ", {clause} = \"{name}\"");
            }
        }
        attributes.push(reference);
    }

    // Field spelling: keywords escape as raw identifiers; the four names
    // Rust reserves outright get a synthetic field mapped back onto the
    // column through the derive's own column attribute.
    let field_name = if RESERVED_NAMES.contains(&column.name()) {
        attributes.push(format!("column = \"{}\"", string_literal(column.name())));
        format!("{}_field", column.name().to_lowercase())
    } else if RAW_ONLY_KEYWORDS.contains(&column.name()) {
        format!("r#{}", column.name())
    } else {
        column.name().to_owned()
    };

    for attribute in &attributes {
        let _ = writeln!(source, "    #[jet({attribute})]");
    }
    let field_type = if column.is_nullable() {
        format!("Option<{rust_type}>")
    } else {
        rust_type
    };
    let _ = writeln!(source, "    pub {field_name}: {field_type},");
}

const fn action_attribute(action: ReferentialAction) -> Option<&'static str> {
    match action {
        ReferentialAction::NoAction => None,
        ReferentialAction::Restrict => Some("restrict"),
        ReferentialAction::Cascade => Some("cascade"),
        ReferentialAction::SetNull => Some("set_null"),
        ReferentialAction::SetDefault => Some("set_default"),
        _ => None,
    }
}

fn field_type_of(column_type: ColumnType) -> String {
    if let ColumnType::ArrayOf(element) = column_type {
        return format!("Vec<{}>", rust_type_of(element.as_column_type()));
    }
    rust_type_of(column_type).to_owned()
}

const fn rust_type_of(column_type: ColumnType) -> &'static str {
    match column_type {
        ColumnType::Boolean => "bool",
        ColumnType::Int16 => "i16",
        ColumnType::Int32 => "i32",
        ColumnType::Int64 => "i64",
        ColumnType::Float32 => "f32",
        ColumnType::Float64 => "f64",
        ColumnType::Decimal => "rust_decimal::Decimal",
        ColumnType::Text => "String",
        ColumnType::Bytes => "Vec<u8>",
        ColumnType::Date => "chrono::NaiveDate",
        ColumnType::Time => "chrono::NaiveTime",
        ColumnType::Timestamp => "chrono::NaiveDateTime",
        ColumnType::TimestampUtc => "chrono::DateTime<chrono::Utc>",
        ColumnType::Uuid => "uuid::Uuid",
        ColumnType::Json => "serde_json::Value",
        // Reached only through scalar element mapping; arrays route
        // through field_type_of.
        ColumnType::ArrayOf(_) => "unreachable",
    }
}

fn pascal_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    let mut upper_next = true;
    for character in input.chars() {
        // Any separator — `_` in identifiers, `-` or spaces in enum
        // labels — starts a new word and vanishes from the spelling.
        if !character.is_alphanumeric() {
            upper_next = true;
        } else if upper_next {
            output.extend(character.to_uppercase());
            upper_next = false;
        } else {
            output.push(character);
        }
    }
    output
}

fn snake_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len() + 4);
    for (index, character) in input.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                output.push('_');
            }
            output.extend(character.to_lowercase());
        } else {
            output.push(character);
        }
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use jetorm_schema::TableName;

    fn schema_with_enum() -> SchemaSet {
        let mut schema = SchemaSet::new();
        schema.insert_enum(
            "post_status",
            ["draft", "in-review", "published"].map(str::to_owned),
        );
        schema.insert(
            TableDef::new(TableName::new("posts"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_column(
                    ColumnDef::new("status", ColumnType::Text).with_type_name("post_status"),
                )
                .with_primary_key(["id".to_owned()]),
        );
        schema
    }

    #[test]
    fn enums_generate_jet_enum_types_and_typed_fields() {
        let generated = entities_source(&schema_with_enum());
        for expected in [
            "#[jet(native = \"post_status\")]",
            "pub enum PostStatus {",
            "    Draft,",
            "#[jet(rename = \"in-review\")]",
            "    InReview,",
            "    Published,",
            "pub status: PostStatus,",
        ] {
            assert!(
                generated.source.contains(expected),
                "generated source lacks {expected:?}:\n{}",
                generated.source
            );
        }
        // `draft` and `published` reproduce from their variant names, so
        // only the dashed label needs an explicit stored name.
        assert_eq!(generated.source.matches("rename").count(), 1);
        assert!(generated.warnings.is_empty(), "{:?}", generated.warnings);
    }

    #[test]
    fn an_enum_named_like_a_table_takes_a_distinct_spelling() {
        let mut schema = schema_with_enum();
        schema.insert_enum("posts", ["a", "b"].map(str::to_owned));
        schema.insert(
            TableDef::new(TableName::new("labels"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_column(ColumnDef::new("kind", ColumnType::Text).with_type_name("posts"))
                .with_primary_key(["id".to_owned()]),
        );
        let generated = entities_source(&schema);
        assert!(
            generated.source.contains("pub enum PostsEnum {"),
            "the table keeps the plain name:\n{}",
            generated.source
        );
        assert!(generated.source.contains("pub kind: PostsEnum,"));
    }

    #[test]
    fn unrepresentable_labels_skip_the_column_with_a_warning() {
        let mut schema = SchemaSet::new();
        // Both labels case to the same identifier — no distinct spelling.
        schema.insert_enum("clash", ["draft", "Draft"].map(str::to_owned));
        schema.insert(
            TableDef::new(TableName::new("posts"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_column(ColumnDef::new("state", ColumnType::Text).with_type_name("clash"))
                .with_primary_key(["id".to_owned()]),
        );
        let generated = entities_source(&schema);
        assert!(
            !generated.source.contains("pub enum"),
            "no enum should generate:\n{}",
            generated.source
        );
        // A String field on an enum-typed column would neither bind nor
        // decode; the column is omitted, not misrepresented.
        assert!(
            !generated.source.contains("pub state"),
            "the untypeable column is omitted:\n{}",
            generated.source
        );
        assert!(
            generated
                .warnings
                .iter()
                .any(|warning| warning.contains("clash") && warning.contains("omitted")),
            "the omission is reported: {:?}",
            generated.warnings
        );
    }

    #[test]
    fn names_and_labels_are_escaped_into_valid_rust_literals() {
        let mut schema = SchemaSet::new();
        // A quote and a backslash — both legal in PostgreSQL enum labels —
        // must not break out of the generated string literal.
        schema.insert_enum("mood", ["say \"hi\"", "back\\slash"].map(str::to_owned));
        schema.insert(
            TableDef::new(TableName::new("posts"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_column(ColumnDef::new("mood", ColumnType::Text).with_type_name("mood"))
                .with_primary_key(["id".to_owned()]),
        );
        let generated = entities_source(&schema);
        assert!(
            generated
                .source
                .contains("#[jet(rename = \"say \\\"hi\\\"\")]"),
            "the quote is escaped:\n{}",
            generated.source
        );
        assert!(
            generated
                .source
                .contains("#[jet(rename = \"back\\\\slash\")]"),
            "the backslash is escaped:\n{}",
            generated.source
        );
        assert!(generated.warnings.is_empty(), "{:?}", generated.warnings);
    }

    #[test]
    fn a_newline_in_a_type_name_cannot_escape_the_doc_comment() {
        let mut schema = SchemaSet::new();
        schema.insert_enum("order\nstatus", ["a"].map(str::to_owned));
        let generated = entities_source(&schema);
        assert!(
            generated
                .source
                .contains("/// Values of the `order status` enum type."),
            "the newline is flattened inside the comment:\n{}",
            generated.source
        );
        assert!(
            generated
                .source
                .contains("#[jet(native = \"order\\nstatus\")]"),
            "the literal keeps the exact name, escaped:\n{}",
            generated.source
        );
    }

    #[test]
    fn prelude_names_are_never_shadowed() {
        let mut schema = SchemaSet::new();
        schema.insert_enum("string", ["a", "b"].map(str::to_owned));
        schema.insert(
            TableDef::new(TableName::new("users"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_column(ColumnDef::new("email", ColumnType::Text))
                .with_column(ColumnDef::new("kind", ColumnType::Text).with_type_name("string"))
                .with_primary_key(["id".to_owned()]),
        );
        let generated = entities_source(&schema);
        assert!(
            generated.source.contains("pub enum StringEnum {"),
            "the enum steps aside for the prelude:\n{}",
            generated.source
        );
        assert!(generated.source.contains("pub email: String,"));
        assert!(generated.source.contains("pub kind: StringEnum,"));
    }

    #[test]
    fn the_collision_suffix_loops_until_the_name_is_free() {
        let mut schema = SchemaSet::new();
        schema.insert_enum("status_", ["a"].map(str::to_owned));
        schema.insert(
            TableDef::new(TableName::new("status"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_primary_key(["id".to_owned()]),
        );
        schema.insert(
            TableDef::new(TableName::new("status_enum"))
                .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                .with_primary_key(["id".to_owned()]),
        );
        let generated = entities_source(&schema);
        // Status and StatusEnum belong to the tables; the enum keeps
        // suffixing until it finds an unclaimed name.
        assert!(
            generated.source.contains("pub enum StatusEnumEnum {"),
            "the suffix re-checks the claimed set:\n{}",
            generated.source
        );
        assert!(generated.source.contains("pub struct Status {"));
        assert!(generated.source.contains("pub struct StatusEnum {"));
    }

    #[test]
    fn tables_casing_identically_take_distinct_struct_names() {
        let mut schema = SchemaSet::new();
        for name in ["user_role", "user-role"] {
            schema.insert(
                TableDef::new(TableName::new(name))
                    .with_column(ColumnDef::new("id", ColumnType::Int64).auto_increment())
                    .with_primary_key(["id".to_owned()]),
            );
        }
        let generated = entities_source(&schema);
        assert!(generated.source.contains("pub struct UserRole {"));
        assert!(
            generated.source.contains("pub struct UserRoleTable {"),
            "the second table steps aside:\n{}",
            generated.source
        );
        assert!(
            generated.warnings.iter().any(|w| w.contains("UserRole")),
            "the rename is reported: {:?}",
            generated.warnings
        );
    }

    #[test]
    fn non_xid_labels_are_rejected_not_emitted() {
        let mut schema = SchemaSet::new();
        // '²' counts as alphanumeric but no Rust identifier may hold it.
        schema.insert_enum("units", ["m²", "m³"].map(str::to_owned));
        let generated = entities_source(&schema);
        assert!(
            !generated.source.contains("pub enum"),
            "no broken identifiers are emitted:\n{}",
            generated.source
        );
        assert!(
            generated.warnings.iter().any(|w| w.contains("units")),
            "{:?}",
            generated.warnings
        );
    }
}
